/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.DepartMent;
import com.founder.enp.entity.LogEntity;
import com.founder.enp.forms.DepartMentsForm;
import com.founder.enp.service.DepartMentService;

/**
 * MyEclipse Struts Creation date: 07-05-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class DepartMentAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub

		String oper = request.getParameter("oper");
		DepartMentService service = new DepartMentService();
		if (oper.equals("query")) {
			int id = Integer.parseInt(request.getParameter("id"));
			DepartMent dpm = service.queryDpmInfo(id);
			if (dpm == null) {
				return mapping.findForward("querydmperror");
			}
			request.setAttribute("departMentsForm", dpm);
			return mapping.findForward("query");
		}
		LogEntity logEntity = new LogEntity();
		logEntity.setActiontype("部门管理");
		if (oper.equals("del"))
		{
			int f = service.delete(Integer.parseInt(request.getParameter("id")));
			if (f == 2)
			{
				logEntity.setAction("删除部门失败");
				request.setAttribute("oper", "notdel");
			}
			else if (f ==1)
			{
				logEntity.setAction("删除部门成功");
				request.setAttribute("oper", "delsuccess");
			}
			else if (f == 0)
			{
				logEntity.setAction("删除部门失败");
				request.setAttribute("oper", "delerror");
			}
			com.founder.enp.service.LogService.recordLog(logEntity, request);
			return mapping.findForward("info");
		}
		DepartMentsForm dpfrm = (DepartMentsForm) form;
		DepartMent dp = new DepartMent();

		if (oper.equals("edit")) {
			dp.setId(dpfrm.getId());

			dp.setName(dpfrm.getName());
			if (service.edit(dp)) {
				logEntity.setAction("修改部门成功");
				request.setAttribute("oper", "editdmpsuccess");
			} else {
				logEntity.setAction("修改部门失败");
				request.setAttribute("oper", "editdmpsuccess");
			}
		}
		if (oper.equals("add")) {
			dp.setName(dpfrm.getName());
			dp.setParentid(dpfrm.getParentID());
			if (service.addDepartMent(dp)) {
				logEntity.setAction("增加部门成功");
				request.setAttribute("oper", "adddmpsuccess");
			} else {
				logEntity.setAction("增加部门失败");
				request.setAttribute("oper", "adddmperror");
			}
		}
		com.founder.enp.service.LogService.recordLog(logEntity, request);
		return mapping.findForward("info");
	}
}