/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.alibaba.fastjson.JSON;
import com.founder.enp.entity.LogEntity;
import com.founder.enp.forms.DocsForm;
import com.founder.enp.service.DocService;
import com.roc.sysmanager.base.service.ClienService;
import com.roc.syspe.entity.OpOrdertickets;
import com.roc.syspe.entity.OpOrderticketsKeyword;

/**
 * MyEclipse Struts Creation date: 07-20-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class DocAction extends DispatchAction {
	//通过身份证获得当日航班的信息列表
	public ActionForward getUserFlightInfos(ActionMapping mapping, ActionForm form,
					HttpServletRequest request, HttpServletResponse response) throws IOException{
			String idCard =  request.getParameter("idcard");
			String ids =  request.getParameter("ids");
			PrintWriter out = response.getWriter();
			if (StringUtils.isEmpty(idCard) 
					&& StringUtils.isEmpty(ids)) {
				out.print("");
				return null;
			}
			ClienService service = new ClienService();
			OpOrderticketsKeyword keyWord = new OpOrderticketsKeyword();
			List<OpOrdertickets> ol  = null;
			if(StringUtils.isEmpty(ids)) {
				keyWord.setCertNo(idCard);
				SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
				keyWord.setStartDate(format.format(new Date()));
			}else {
				keyWord.setIds(ids);
			}
			ol = service.teamDjpListByIdCard(keyWord);
			ol = ol == null ?new ArrayList():ol;
			String json = JSON.toJSONString(ol);
			out.print(json);
			return null;
	}
}