/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.service.LogService;
import com.founder.enp.entity.LogEntity;
import com.founder.enp.entity.LogKeyWord;
import com.founder.enp.util.Global;

/**
 * MyEclipse Struts Creation date: 07-19-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class LogAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String oper = request.getParameter("oper");
		if (oper.equals("list")) {
			int currentPage = Integer.parseInt(request
					.getParameter("currentPage") == null ? "1" : request
							.getParameter("currentPage"));
			String beginDate = request.getParameter("beginDate");
			String endDate = request.getParameter("endDate");
			int count = 0;
			java.util.List logList = null;
			LogKeyWord logkw = new LogKeyWord();
			logkw.setPageInfo(20, currentPage);
			if (beginDate != null) {
				logkw.setStartDate(beginDate);
				logkw.setEndDate(endDate);
			}
			count = LogService.getLogCount(logkw);
			logList = LogService.getLogList(logkw);
			if (count == -1 || logList == null) {
				request.setAttribute("oper", "listerror");
				return mapping.findForward("info");
			}
			request.setAttribute("keyword", logkw);
			request.setAttribute("count", Integer.valueOf(count));
			request.setAttribute("currentPage", Integer.valueOf(currentPage));
			request.setAttribute("pageCount", Integer.valueOf(Global
					.computePageCount(count)));
			request.setAttribute("list", logList);
			return mapping.findForward("list");
		}
		else if (oper.equals("del"))
		{
			String idString  = request.getParameter("idString");
			LogEntity logEntity = new LogEntity();
			logEntity.setActiontype("日志管理");
			if (LogService.delete(idString))
			{
				logEntity.setAction("删除系统日志成功");
				request.setAttribute("oper", "delsuccess");
			}
			else
			{
				logEntity.setAction("删除系统日志失败");
				request.setAttribute("oper", "delerror");
			}
			com.founder.enp.service.LogService.recordLog(logEntity, request);
			return mapping.findForward("info");
		}
		return null;
	}
}