/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.LogEntity;
import com.founder.enp.entity.Parameter;
import com.founder.enp.forms.ParameterForm;
import com.founder.enp.service.ParameterService;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ParameterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		String oper = request.getParameter("oper");
		ParameterService service = new ParameterService();
		if (oper.equals("list"))
		{
			Parameter para = service.listParameter();
			if (para == null)
			{
				request.setAttribute("oper","listerror");
				return mapping.findForward("info");
			}
			request.setAttribute("parameterForm", para);
			return mapping.findForward("list");
	
		}
		if (oper.equals("update"))
		{
			ParameterForm frm = (ParameterForm)form;
			Parameter param = new Parameter();
			param.setAttacheip(frm.getAttacheip());
			param.setContentip(frm.getContentip());
			param.setDocsbackip(frm.getDocsbackip());
			param.setTemplateip(frm.getTemplateip());
			param.setHttpdnload(frm.getHttpdnload());
			param.setHttpupload(frm.getHttpupload());
			LogEntity logEntity = new LogEntity();
			logEntity.setActiontype("参数设置");
			if (service.update(param))
			{
				logEntity.setAction("更新参数设置成功");
				request.setAttribute("oper", "updatesuccess");
			}
			else
			{
				logEntity.setAction("更新参数设置失败");
				request.setAttribute("oper", "updateerror");
			}
			com.founder.enp.service.LogService.recordLog(logEntity, request);
			return mapping.findForward("info");
		}
		return null;
	}
}