/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.Parameter;
import com.founder.enp.forms.SelectTemplateForm;
import com.founder.enp.service.ParameterService;
import com.founder.enp.util.ContentNameUtil;

/**
 * MyEclipse Struts Creation date: 07-20-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class SelectTemplateAction extends Action {
	/*
	 * Generated Methods
	 */
	private static Log log = LogFactory.getLog(SelectTemplateAction.class);
	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		SelectTemplateForm fm = (SelectTemplateForm) form;
		// 不是引入就是新建
		String filePath = fm.getContent();
		ParameterService service = new ParameterService();
		Parameter param = service.listParameter();
		if (fm.getSelect() == 2) {
			filePath = param.getHttpdnload()+"template/"+fm.getContent();
		} 
		else
		{
			filePath = filePath.replace("\\", "\\\\");
		}

		String uploadContent = param.getContentip()+ContentNameUtil.GetContentName()+filePath.substring(filePath.lastIndexOf("."),filePath.length());
		fm.setContentName(uploadContent.replace("\\",  "\\\\"));
		fm.setContent(filePath);
		request.getSession().setAttribute("selectTemplate", fm);
		return mapping.findForward("openTemplate");

	}
}