/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.service.UserService;

/**
 * MyEclipse Struts Creation date: 08-12-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class UnloadAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UserService service = new UserService();
		service.unload(request);
		HttpSession session = request.getSession(true);
		try {
			if (!session.isNew()) {
				session.invalidate();
				session = request.getSession(true);
			}
		} catch (Exception exception) {
		}
		return null;
	}
}