/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2009
 * 
 * XDoclet definition:
 * @struts.form name="parameterForm"
 */
public class ParameterForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	 private String templateip;
	 private String attacheip;
	 private String contentip;
	 private String docsbackip;
	 private String httpupload;
	 private String httpdnload;
	 
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getAttacheip() {
		return attacheip;
	}

	public void setAttacheip(String attacheip) {
		this.attacheip = attacheip;
	}

	public String getContentip() {
		return contentip;
	}

	public void setContentip(String contentip) {
		this.contentip = contentip;
	}

	public String getDocsbackip() {
		return docsbackip;
	}

	public void setDocsbackip(String docsbackip) {
		this.docsbackip = docsbackip;
	}
	public String getTemplateip() {
		return templateip;
	}

	public void setTemplateip(String templateip) {
		this.templateip = templateip;
	}

	public String getHttpdnload() {
		return httpdnload;
	}

	public void setHttpdnload(String httpdnload) {
		this.httpdnload = httpdnload;
	}

	public String getHttpupload() {
		return httpupload;
	}

	public void setHttpupload(String httpupload) {
		this.httpupload = httpupload;
	}
}