/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.Flows;
import com.founder.enp.entity.LogEntity;
import com.founder.enp.forms.SubmitForm;
import com.founder.enp.service.DocService;

/** 
 * MyEclipse Struts
 * Creation date: 08-05-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class RejectAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		DocService service = new DocService();
		String oper = request.getParameter("oper");
		if (oper.equals("check"))
		{
			response.setHeader("Cache-Control", "no-store");
			response.setHeader("Pragma", "no-cache");
			response.setDateHeader("Expires", 0L);
			String flowsid = request.getParameter("flowids");
			String info="";
			if (service.chekcRejectDoc(flowsid))
			{
				info="noReject";
			}
			PrintWriter out = null;
			try {
				out = response.getWriter();
			} catch (Exception exception) {
			}
			out.print(info);
			out.close();
		}
		if (oper.equals("submit"))
		{
			SubmitForm frm = (SubmitForm)form;
			LogEntity logEntity = new LogEntity();
			logEntity.setActiontype("驳回公文");
			String tip = "";
			if (service.RejectDoc(frm, request))
			{
				logEntity.setAction("驳回公文成功");
				tip = "rejectsuccess";
			}
			else
			{
				logEntity.setAction("驳回公文失败");
				tip = "rejecterror";
			}
			com.founder.enp.service.LogService.recordLog(logEntity, request);
			request.setAttribute("oper", tip);
			return mapping.findForward("tip");
		}
		return null;
	}
}