/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.Authorization;
import com.founder.enp.service.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class AdviceAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		UserService service = new UserService();
		String oper = request.getParameter("oper");
		if (oper.equals("del"))
		{
			String info = "";
			String adsid = request.getParameter("adsid");
			if (service.delAdvice(Integer.parseInt(adsid)))
			{
				info="delok";
				
			}
			else
			{
				info="delerror";
			}
			response.setHeader("Cache-Control", "no-store");
			response.setHeader("Pragma", "no-cache");
			response.setDateHeader("Expires", 0L);
			PrintWriter out = null;
			try {
				out = response.getWriter();
			} catch (Exception exception) {
			}
			out.print(info);
			out.close();
		}
		else
		{
		Authorization authorization = (Authorization) request.getSession()
		.getAttribute("authorization");
		List list = service.getAdvice(authorization.getUserid());
		request.setAttribute("list", list);
		
		return mapping.findForward("list");
		}
		return null;
	}
}