/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.LogEntity;
import com.founder.enp.service.DocService;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class WithDrawAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		DocService serivce = new DocService();
		String flowsid = request.getParameter("flowids");
		String info="";
		LogEntity logEntity = new LogEntity();
		logEntity.setActiontype("撤回公文");
		int f = serivce.withDrawDoc(request,flowsid);
		if (f == 2 || f == 4)
		{
			info = "nowithDraw";
			logEntity.setAction("撤回公文失败");
		}
		else if (f == 1)
		{
			info = "yeswithDraw";
			logEntity.setAction("撤回公文成功");
		}
		else if (f == 3)
		{
			info = "nowithDrawSelf";
			logEntity.setAction("撤回公文失败");
		}
		else
		{
			info = "nowithDraw";
			logEntity.setAction("撤回公文失败");
		}
		response.setHeader("Cache-Control", "no-store");
		response.setHeader("Pragma", "no-cache");
		response.setDateHeader("Expires", 0L);
		com.founder.enp.service.LogService.recordLog(logEntity, request);
		PrintWriter out = null;
		try {
			out = response.getWriter();
		} catch (Exception exception) {
		}
		out.print(info);
		out.close();
		return null;
	}
}