/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.DocEntity;
import com.founder.enp.entity.LogEntity;
import com.founder.enp.forms.DocsForm;
import com.founder.enp.service.DocService;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class DocFinishAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		DocsForm docsForm = (DocsForm)form;
		DocEntity docEntity = new DocEntity();

		docEntity.setCopyto(docsForm.getCopyto());

		docEntity.setCreatemode(docsForm.getCreatemode());
		docEntity.setCreateorg(docsForm.getCreateorg());
		docEntity.setKeywords(docsForm.getKeywords());
		docEntity.setPrintnum(docsForm.getPrintnum());
		docEntity.setPublishlevel(docsForm.getPublishlevel());
		docEntity.setPublishOrg(docsForm.getPublishOrg());
		docEntity
				.setPublishtime(docsForm.getPublishtime().equals("") ? null
						: docsForm.getPublishtime());
		docEntity.setSecret(docsForm.getSecret());
		docEntity.setSecretime(docsForm.getSecretime());
		docEntity.setTitle(docsForm.getTitle());
		docEntity.setToOrg(docsForm.getToOrg());
		docEntity.setTypename(docsForm.getTypename());
		docEntity.setCreator(docsForm.getCreator());
		docEntity.setUrgence(docsForm.getUrgence());
		docEntity.setDocid(docsForm.getDocid());
		docEntity.setDocnum(docsForm.getDocnum());
		docEntity.setMaketime(docsForm.getMaketime());
		DocService serivce = new DocService();
		LogEntity logEntity = new LogEntity();
		logEntity.setActiontype("审批完毕");
		String info = "";
	    /*if (serivce.modifyDoc(docEntity,request))
	    {
	    	info = "finishsuccess";
			logEntity.setAction("办结公文成功");
	    }
	    else
	    {
	    	info = "finisherror";
			logEntity.setAction("办结公文失败");
	    }*/
	    request.setAttribute("oper", info);
	    com.founder.enp.service.LogService.recordLog(logEntity, request);
		return mapping.findForward("info");
	}
}