/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.forms;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.Template;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2009
 * 
 * XDoclet definition:
 * @struts.form name="docTypesForm"
 */
public class DocTypesForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*
	 * Generated Methods
	 */
	private Integer doctypeid;
	private String typename;
	private Integer dmpid;
	private Integer templetid;
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Integer getDmpid() {
		return dmpid;
	}

	public void setDmpid(Integer dmpid) {
		this.dmpid = dmpid;
	}

	public Integer getDoctypeid() {
		return doctypeid;
	}

	public void setDoctypeid(Integer doctypeid) {
		this.doctypeid = doctypeid;
	}

	public Integer getTempletid() {
		return templetid;
	}

	public void setTempletid(Integer templetid) {
		this.templetid = templetid;
	}

	public String getTypename() {
		return typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}


}