/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.entity.LogEntity;
import com.founder.enp.forms.SubmitForm;
import com.founder.enp.service.DocService;

/** 
 * MyEclipse Struts
 * Creation date: 08-08-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class AuditFinishAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String oper = request.getParameter("oper");
		DocService service = new DocService();
		if (oper.equals("auditFinish"))
		{
			SubmitForm frm = (SubmitForm)form;
			LogEntity logEntity = new LogEntity();
			logEntity.setActiontype("签批公文");
			String tip = "";
			if (service.auditFinish(frm, request))
			{
				logEntity.setAction("签批公文成功");
				tip = "auditfinishsuccess";
			}
			else
			{
				logEntity.setAction("签批公文失败");
				tip = "auditfinisherror";
			}
			com.founder.enp.service.LogService.recordLog(logEntity, request);
			request.setAttribute("oper", tip);
			return mapping.findForward("tip");
		}
		
		return null;
	}
}