/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.founder.enp.action;

import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.founder.enp.service.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 07-13-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class CheckAccountAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		 PrintWriter out = null;
	        try
	        {
	            out = response.getWriter();
	        }
	        catch(Exception exception) { }
	        String account = request.getParameter("account");
	        UserService service = new UserService();
	        int count = service.checkAccount(account);
	        if(count > 0)
	            out.print("no");
	        else
	            out.print("yes");
	        out.close();
	        return null;
	}
}